config/routes.rb
Rails.application.routes.draw do
  devise_for :empleados
  root "static#main"

  resources :clientes
  resources :disenos
  resources :empleados
  resources :categories
  resources :tamanos
  resources :productos
end

app/models/diseno.rb
class Diseno < ActiveRecord::Base
  has_and_belongs_to_many :productos

  mount_uploader :diseno, DisenoUploader

  validates_processing_of :diseno
  validate :diseno_size_validation

  private
  def diseno_size_validation
    errors[:diseno] << "Debe de ser menor a 2 MB" if diseno.size > 2.megabytes
  end
end

app/controllers/disenos_controller.rb
class DisenosController < ApplicationController
  before_action :set_disenos, except: [:index, :new, :create]
  before_action :authenticate_empleado!,  except: [:index, :show]


  def new
    @diseno=Diseno.new
  end

  def create
    @diseno= Diseno.new(params_disenos)

    respond_to do |format|
      if @diseno.save
        format.html { redirect_to @diseno, notice: 'El diseño se ha creado exitosamente.' }
        format.json { render :show, status: :created, location: @diseno }
      else
        format.html { render :new }
        format.json { render json: @diseno.errors, status: :unprocessable_entity }
      end
    end
  end

  def show
  end

  def index
    @diseno=Diseno.all
  end

  def edit
  end

  def update
    respond_to do |format|
      if @diseno.update(params_disenos)
        format.html { redirect_to @diseno, notice: 'El diseño se ha actualizado exitosamente' }
        format.json { render :show, status: :ok, location: @diseno }
      else
        format.html { render :edit }
        format.json { render json: @diseno.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @diseno.destroy
    respond_to do |format|
      format.html { redirect_to disenos_path, notice: 'El diseño ha sido eliminado.' }
      format.json { head :no_content }
    end
  end

  def set_disenos
    @diseno=Diseno.find(params[:id])
  end

  private
  def params_disenos
    params.require(:diseno).permit(:nombre, :diseno)
  end


end

app/helpers/disenos_helper.rb
module DisenosHelper
end

app/views/disenos/_form.html.erb
<h1><%= name %> diseño</h1>
<div class="well">
<%= form_for (@diseno) do |f| %>
    <% if @diseno.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@tamano.errors.count, "error") %> no es posible
            guardar este diseño por que no se cumple con el formato siguiente:</h2>
          <ul>
            <% @diseno.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>
    <div class="field">
      <%= f.label :nombre %><br>
      <%= f.text_field :nombre, :class=>'form-control' , :placeholder=>'Escriba el nombre del diseño (Ej. Flores)' %>
    </div>

    <div class="field">
      <%= f.label :diseno %><br>
      <%= f.file_field :diseno %>
      <% if f.object.diseno? %>
          <%= image_tag f.object.diseno.thumb.url %>
          <%= f.label :eliminar_diseno %>
          <%= f.check_box :remove_diseno %>
      <% end %>
    </div>

    <p>
      <%= f.submit 'Guardar Diseño', class: 'btn btn-success btn-sm' %>
    </p>
<% end %>
  </div>

app/views/disenos/edit.html.erb
<div class="container">
<%= render 'form',  name: 'Editar' %>
<%= link_to 'Atras', disenos_path, class: 'btn btn-primary btn-sm'   %>
</div>

app/views/disenos/index.html.erb
<div class="container">
<h1>Catalogo de Diseños </h1>
  <div class="well">
    <% if empleado_signed_in?  %>
      <%= link_to 'Nuevo Diseño', new_diseno_path, class: 'btn btn-success btn-sm'  %>
    <% end %>

<% if !@diseno.blank? %>
    <table border="2" class="table table-bordered">
      <tr>
        <th>Nombre</th>
        <th>Diseño</th>
      </tr>

      <% @diseno.each do |d| %>
          <tr>
            <td><%= d.nombre %></td>
            <td> <%=image_tag d.diseno.thumb.url,  class:'img-responsive img-thumbnail' if d.diseno.present? %></td>
            <td><%= link_to 'Ver', diseno_path(d),  class: 'glyphicon glyphicon-eye-open btn btn-info btn-sm ' %></td>
            <% if empleado_signed_in?  %>
              <td><%= link_to 'Modificar', edit_diseno_path(d), class: 'btn btn-warning btn-sm' %></td>
              <td><%= link_to 'Borrar', diseno_path(d), class: 'btn btn-danger btn-sm',
                            method: :delete,  data: { confirm: '¿Seguro que desea eliminar este diseño?' } %></td>
             <% end %>
                </tr>
      <% end %>
    </table>
<% else %>
    <br/>
    <h3>No hay registros</h3>
    <br/>
<% end %>
  </div>
</div>

app/views/disenos/new.html.erb
<div class="container">
<%= render 'form',  name: 'Nuevo' %>
<%= link_to 'Atras', disenos_path,  class: 'btn btn-primary btn-sm'   %>
</div>

app/views/disenos/show.html.erb
<div class="container">
  <h1>Ver Diseño</h1>
  <div class="well">
    <p>
      <%= image_tag @diseno.diseno.thumb.url if @diseno.diseno.present? %>
    </p>
<p>
  <strong>Nombre:</strong>
  <%= @diseno.nombre %>
</p>

<%= link_to 'Regresar' , disenos_path, :class => 'btn  btn-primary btn-sm'%>
| <%= link_to 'Modificar', edit_diseno_path(@diseno), :class => 'btn  btn-warning btn-sm' %>
</div>
  </div>