config/routes.rb
Rails.application.routes.draw do
  devise_for :empleados
  root "static#main"

  resources :clientes
  resources :disenos
  resources :empleados
  resources :categories
  resources :tamanos
  resources :productos
end

app/models/tamano.rb
class Tamano < ActiveRecord::Base
  has_and_belongs_to_many :productos

  validates :tamano, presence:{ message: 'es requerido' }, length: {minimum: 3, maximum:50 , message: 'la longitud debe de ser de entre 3 a 50 caracteres'}
  validates :descripcion, presence: { message: 'es requerido' }
end

app/controllers/tamanos_controller.rb
class TamanosController < ApplicationController
  before_action :set_tamano, except: [:index, :new, :create]
  before_action :authenticate_empleado!,  except: [:index, :show]


  def new
    @tamano=Tamano.new
  end

  def create
    @tamano = Tamano.new(params_tamano)
    respond_to do |format|
      if @tamano.save
        format.html { redirect_to @tamano, notice: 'El tamaño se ha creado exitosamente.' }
        format.json { render :show, status: :created, location: @tamano }
      else
        format.html { render :new }
        format.json { render json: @tamano.errors, status: :unprocessable_entity }
      end
    end
  end

  def index
    @tamano = Tamano.all
  end

  def show
  end

  def edit
  end

  def update
    respond_to do |format|
      if @tamano.update(params_tamano)
        format.html { redirect_to @tamano, notice: 'El tamaño se ha actualizado exitosamente.' }
        format.json { render :show, status: :ok, location: @tamano }
      else
        format.html { render :edit }
        format.json { render json: @tamano.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @tamano.destroy
    respond_to do |format|
      format.html { redirect_to tamanos_path, notice: 'El tamaño ha sido eliminado.' }
      format.json { head :no_content }
    end
  end

  def set_tamano
    @tamano = Tamano.find(params[:id])
  end

  private
  def params_tamano
    params.require(:tamano).permit(:tamano, :descripcion)
  end
end

app/helpers/tamanos_helper.rb
module TamanosHelper
end

app/views/tamanos/_form.html.erb
<h1><%= name %> tamaño</h1>
<div class="well">
<%= form_for (@tamano) do |f| %>
    <% if @tamano.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@tamano.errors.count, "error") %> no es posible
            guardar este tamaño por que no se cumple con el formato siguiente:</h2>
          <ul>
            <% @tamano.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>
    <p>
      <%= f.label :tamano %><br>
      <%= f.text_field :tamano, :class=>'form-control', :placeholder=>'Escriba un tamaño(Ej. Chico)' %>
    </p>

    <p>
      <%= f.label :descripcion %><br>
      <%= f.text_area :descripcion, :class=>'form-control', :placeholder=>'Escriba un la descripcion del tamaño(Ej. Este es el tamaño Chico)'  %>
    </p>

    <p>
      <%= f.submit 'Guardar Tamaño', class: 'btn btn-success btn-sm' %>
    </p>
<% end %>
  </div>

app/views/tamanos/edit.html.erb
<div class="container">
<%= render 'form',  name: 'Editar' %>
<%= link_to 'Regresar' , tamanos_path,  class: 'btn btn-primary btn-sm' %>
</div>

app/views/tamanos/index.html.erb
<div class="container">
<h1>Catalogo de Tamaños </h1>
  <div class="well">
    <% if empleado_signed_in?  %>
      <%= link_to 'Nuevo Tamaño', new_tamano_path, class: 'btn btn-success btn-sm'    %>
    <% end %>
<% if !@tamano.blank? %>
<table border="2" class="table table-bordered">
  <tr>
    <th>Tamaño</th>
    <th>Descripcion</th>
  </tr>

  <% @tamano.each do |t| %>
      <tr>
        <td><%= t.tamano %></td>
        <td><%= t.descripcion  %></td>
        <td><%= link_to 'Ver', tamano_path(t), class: 'btn btn-info btn-sm'%></td>
        <% if empleado_signed_in?  %>
          <td><%= link_to 'Modificar', edit_tamano_path(t),  class: 'btn btn-warning btn-sm' %></td>
          <td><%= link_to 'Borrar', tamano_path(t), class: 'btn btn-danger btn-sm',
                        method: :delete,  data: { confirm: '¿Seguro que desea eliminar este tamaño?' } %></td>
       <% end %>
      </tr>
  <% end %>
</table>
<% else %>
    <br/>
<h3>No hay registros</h3>
    <br/>
<% end %>
    </div>
  </div>

app/views/tamanos/new.html.erb
<div class="container">
<%= render 'form',  name: 'Nuevo' %>
<%= link_to 'Regresar' , tamanos_path,  class: 'btn btn-primary btn-sm'%>
</div>

app/views/tamanos/show.html.erb
<div class="container">
<h1>Ver Tamaño</h1>
<div class="well">
<p>
  <strong>Tamaño:</strong>
  <%= @tamano.tamano %>
</p>

<p>
  <strong>Descripcion:</strong>
  <%= @tamano.descripcion %>
</p>

<%= link_to 'Regresar' , tamanos_path,  class: 'btn btn-primary btn-sm'%>
| <%= link_to 'Modificar', edit_tamano_path(@tamano),  class: 'btn btn-warning btn-sm' %>
</div>
</div>