config/routes.rb
Rails.application.routes.draw do
  devise_for :empleados
  root "static#main"

  resources :clientes
  resources :disenos
  resources :empleados
  resources :categories
  resources :tamanos
  resources :productos
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_and_belongs_to_many :productos

  validates :nombre, presence:{ message: 'es requerido' }, length: {minimum: 3, maximum:50 , message: 'la longitud debe de ser de entre 3 a 50 caracteres'}
  validates :descripcion, presence: { message: 'es requerida' }
end

app/models/cliente.rb
class Cliente < ActiveRecord::Base

end

app/models/diseno.rb
class Diseno < ActiveRecord::Base
  has_and_belongs_to_many :productos

  mount_uploader :diseno, DisenoUploader

  validates_processing_of :diseno
  validate :diseno_size_validation

  private
  def diseno_size_validation
    errors[:diseno] << "Debe de ser menor a 2 MB" if diseno.size > 2.megabytes
  end
end

app/models/empleado.rb
class Empleado < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/estado.rb
class Estado < ActiveRecord::Base
end

app/models/paise.rb
class Paise < ActiveRecord::Base
end

app/models/producto.rb
class Producto < ActiveRecord::Base
  has_and_belongs_to_many :tamanos
  has_and_belongs_to_many :categories
  has_and_belongs_to_many :disenos

  mount_uploader :fotografia, FotografiaUploader

  validates_processing_of :fotografia
  validate :fotografia_size_validation

  private
  def fotografia_size_validation
    errors[:fotografia] << "Debe de ser menor a 2 MB" if fotografia.size > 2.megabytes
  end
end

app/models/tamano.rb
class Tamano < ActiveRecord::Base
  has_and_belongs_to_many :productos

  validates :tamano, presence:{ message: 'es requerido' }, length: {minimum: 3, maximum:50 , message: 'la longitud debe de ser de entre 3 a 50 caracteres'}
  validates :descripcion, presence: { message: 'es requerido' }
end

app/controllers/disenos_controller.rb
class DisenosController < ApplicationController
  before_action :set_disenos, except: [:index, :new, :create]
  before_action :authenticate_empleado!,  except: [:index, :show]


  def new
    @diseno=Diseno.new
  end

  def create
    @diseno= Diseno.new(params_disenos)

    respond_to do |format|
      if @diseno.save
        format.html { redirect_to @diseno, notice: 'El diseño se ha creado exitosamente.' }
        format.json { render :show, status: :created, location: @diseno }
      else
        format.html { render :new }
        format.json { render json: @diseno.errors, status: :unprocessable_entity }
      end
    end
  end

  def show
  end

  def index
    @diseno=Diseno.all
  end

  def edit
  end

  def update
    respond_to do |format|
      if @diseno.update(params_disenos)
        format.html { redirect_to @diseno, notice: 'El diseño se ha actualizado exitosamente' }
        format.json { render :show, status: :ok, location: @diseno }
      else
        format.html { render :edit }
        format.json { render json: @diseno.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @diseno.destroy
    respond_to do |format|
      format.html { redirect_to disenos_path, notice: 'El diseño ha sido eliminado.' }
      format.json { head :no_content }
    end
  end

  def set_disenos
    @diseno=Diseno.find(params[:id])
  end

  private
  def params_disenos
    params.require(:diseno).permit(:nombre, :diseno)
  end


end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def main
  end
end

app/controllers/tamanos_controller.rb
class TamanosController < ApplicationController
  before_action :set_tamano, except: [:index, :new, :create]
  before_action :authenticate_empleado!,  except: [:index, :show]


  def new
    @tamano=Tamano.new
  end

  def create
    @tamano = Tamano.new(params_tamano)
    respond_to do |format|
      if @tamano.save
        format.html { redirect_to @tamano, notice: 'El tamaño se ha creado exitosamente.' }
        format.json { render :show, status: :created, location: @tamano }
      else
        format.html { render :new }
        format.json { render json: @tamano.errors, status: :unprocessable_entity }
      end
    end
  end

  def index
    @tamano = Tamano.all
  end

  def show
  end

  def edit
  end

  def update
    respond_to do |format|
      if @tamano.update(params_tamano)
        format.html { redirect_to @tamano, notice: 'El tamaño se ha actualizado exitosamente.' }
        format.json { render :show, status: :ok, location: @tamano }
      else
        format.html { render :edit }
        format.json { render json: @tamano.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @tamano.destroy
    respond_to do |format|
      format.html { redirect_to tamanos_path, notice: 'El tamaño ha sido eliminado.' }
      format.json { head :no_content }
    end
  end

  def set_tamano
    @tamano = Tamano.find(params[:id])
  end

  private
  def params_tamano
    params.require(:tamano).permit(:tamano, :descripcion)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/clientes_helper.rb
module ClientesHelper
end

app/helpers/disenos_helper.rb
module DisenosHelper
end

app/helpers/empleados_helper.rb
module EmpleadosHelper
end

app/helpers/productos_helper.rb
module ProductosHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/tamanos_helper.rb
module TamanosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <title><%= content_for?(:title) ? yield(:title) : "Artesanias Yessy" %></title>


  </head>
  <header>
  </header>

  <body>
  <%= render 'templates/menu' %>
  <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
  <% end %>
  <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
  <% end %>
    <%= yield %>

  </body>
  <footer>
    <%= render 'templates/footer' %>
  </footer>
</html>

app/views/templates/_footer.html.erb
<div class="center-block">
  <h3>Artesanias Yessy 2016</h3>
</div>

app/views/templates/_menu.html.erb
<nav class="navbar navbar-default" style="margin-:0px;">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="<%= root_path %>">Artesanias Yessy</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <% if current_empleado.nil? %>
            <li><a href="<%= root_path %>">Inicio <span class="sr-only">(current)</span></a></li>
      <% else %>
            <li><a href="<%= root_path %>">Inicio <span class="sr-only">(current)</span></a></li>
            <li><a href="<%= productos_path %>">Productos</a></li>
              <li><a href="<%=categories_path %>">Categorias</a></li>
              <li><a href="<%=tamanos_path %>">Tamaños</a></li>
              <li><a href="<%=disenos_path %>">Diseños</a></li>
              <li><a href="<%=clientes_path %>">Clientes</a></li>
              <li><a href="<%=empleados_path %>">Empleados</a></li>
            <%end %>
      </ul>

      <ul class="nav navbar-nav navbar-right">
        <% if current_empleado.nil? %>
            <li><a href="<%= new_empleado_session_path %>">Ingreso</a></li>
            <li><a href="<%= new_empleado_registration_path %>">Registro</a></li>
        <% else %>
            <li><a href="<%= edit_empleado_registration_path %>">Editar Mis Datos</a></li>
            <li><a href="<%= destroy_empleado_session_path %>" data-method="delete">Salir</a></li>
        <%end%>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>