config/routes.rb
Rails.application.routes.draw do
  devise_for :empleados
  root "static#main"

  resources :clientes
  resources :disenos
  resources :empleados
  resources :categories
  resources :tamanos
  resources :productos
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_and_belongs_to_many :productos

  validates :nombre, presence:{ message: 'es requerido' }, length: {minimum: 3, maximum:50 , message: 'la longitud debe de ser de entre 3 a 50 caracteres'}
  validates :descripcion, presence: { message: 'es requerida' }
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
    before_action :set_category, except: [:index, :new, :create]
    before_action :authenticate_empleado!,  except: [:index, :show]

    def new
    @category= Category.new
  end

  def create
    @category= Category.new(params_category)
      respond_to do |format|
        if @category.save
          format.html { redirect_to @category, notice: 'La categoria se ha creado exitosamente.' }
          format.json { render :show, status: :created, location: @category }
        else
          format.html { render :new }
          format.json { render json: @category.errors, status: :unprocessable_entity }
        end
      end
  end

  def show
  end

  def index
    @category=Category.all
  end

  def edit
  end

  def  update
    respond_to do |format|
      if @category.update(params_category)
        format.html { redirect_to @category, notice: 'La categoria se ha actualizado exitosamente.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_path, notice: 'La categoria ha sido eliminado.' }
      format.json { head :no_content }
    end
  end

  def set_category
    @category = Category.find(params[:id])
  end

  private
  def params_category
    params.require(:category).permit(:nombre, :descripcion)
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<h1><%= name %> categoria</h1>
<div class="well">
<%= form_for (@category),  :html => {:multipart => true} do |f| %>
    <% if @category.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@category.errors.count, "errore") %>no es posible
            guardar esta categoria por que no se cumple con el formato siguiente:</h2>
          <ul>
            <% @category.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>
      <div class="form-group">
    <p>
      <%= f.label :nombre %><br>
      <%= f.text_field :nombre , :class=>'form-control' , :placeholder=>'Escriba el nombre de la categoria(Ej. Rana)'%>
    </p>
      </div>

      <div class="form-group">
        <p>
      <%= f.label :descripcion %><br>
      <%= f.text_area :descripcion, :class=>'form-control' , :placeholder=>'Escriba la descripcion de la categoria(Ej. Esta es la categoria para las ranas)' %>
    </p>
      </div>

    <p>
      <%= f.submit 'Guardar Categoria', class: 'btn btn-success btn-sm'  %>
    </p>
<% end %>
</div>

app/views/categories/edit.html.erb
<div class="container">
<%= render 'form',  name: 'Editar' %>
<%= link_to 'Atras', categories_path, class: 'btn btn-primary btn-sm'   %>
</div>

app/views/categories/index.html.erb
<div class="container">
<h1>Catalogo de Categorias</h1>
  <div class="well">
    <% if empleado_signed_in?  %>
      <%= link_to 'Nueva categoria', new_category_path, class: 'btn btn-success btn-sm'   %>
    <% end %>
<% if !@category.blank? %>
<table border="2"  class="table table-bordered">
  <tr>
    <th>Nombre</th>
    <th>Descripcion</th>
  </tr>

  <% @category.each do |c| %>
      <tr>
        <td><%= c.nombre %></td>
        <td><%= c.descripcion %></td>
        <td><%= link_to 'Ver', category_path(c), class: 'btn btn-info btn-sm' %></td>
        <% if empleado_signed_in?  %>
            <td><%= link_to 'Editar', edit_category_path(c), class: 'btn btn-warning btn-sm' %></td>
            <td><%= link_to 'Borrar',category_path(c) , class: 'btn btn-danger btn-sm',
                        method: :delete, data: { confirm: '¿Seguro que desea eliminar esta categoria?'} %></td>
        <% end %>
            </tr>
  <% end %>
</table>
<% else %>
    <br/>
    <h3>No hay registros</h3>
    <br/>
<% end %>
</div>
</div>

app/views/categories/new.html.erb
<div class="container">
  <%= render 'form',  name: 'Nueva' %>
<%= link_to 'Atras', categories_path, class: 'btn btn-primary btn-sm'   %>
</div>

app/views/categories/show.html.erb
<div class="container">
<h1>Ver Categoria</h1>
  <div class="well">
<p>
  <strong>Nombre:</strong>
  <%= @category.nombre %>
</p>

<p>
  <strong>Descripcion:</strong>
  <%= @category.descripcion %>
</p>

<%= link_to 'Regresar', categories_path, class: 'btn btn-primary btn-sm'   %>
| <%= link_to 'Editar', edit_category_path(@category), class: 'btn btn-warning btn-sm'   %>
  </div>
</div>